
ifeq ($(subdir),)
$(error Error: The subdir must not be empty. It should be either "." or a path to the source code subdirectory.)
endif

include .config
-include $(subdir)/obj.mk

obj-y := $(addprefix $(subdir)/,$(obj-y))
src = $(obj-y:.o=.c)
elf-y := $(addprefix $(subdir)/,$(elf-y))

all: $(elf-y) $(lib-y)

# In case no one have configure the build system we will take the default
# configuration
.config: defconfig
	cp $< $@

config.h: .config
	sed -e "/^#/d" \
		-e "s/=y/=1/" \
		-e "s/^\([A-Z_]*\)=\(.*\)$$/#define \1 \2/" $< > $@

# TODO: dependency between .c files and .h should be generated automatically.
$(elf-y): $(src) config.h
	$(CC) $(CFLAGS) $(CPPFLAGS) $^ -o $@

$(lib-y): $(obj-y)
	-rm $@
	$(AR) rcs $@ $^

# TODO: dependency between .c files and .h should be generated automatically.
%.o: %.c config.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

%.s: %.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -S -fverbose-asm $< -o $@

%.lst: %.s
	$(AS) -alhnd $< > $@

$(elf-y).sym: $(elf-y)
	$(NM) -S --size-sort -t d  <$< >$@

clean:
	-rm $(elf-y)
	-rm $(elf-y).sym
	-rm $(lib-y)
	-rm $(subdir)/*.lst
	-rm $(subdir)/*.s
	-rm $(obj-y)
	-rm config.h
	-rm .config


test:
	$(MAKE) clean
	$(MAKE) $(elf-y)
	$(MAKE) $(obj-y:.o=.lst)
	$(MAKE) $(elf-y).sym
	$(MAKE) clean
